spring:
  application:
    name: micro01
  data:
    mongodb:
      ## aquí pondreis la URL que teneis de mongoAtlas, recordar que teneis que poner en la URl despues de .net/<basedatos>?retry...
      ## en caso de tener una mongo en local -> mongodb://localhost:27018/<basededatos>
      uri: mongodb+srv://root:root@cluster0.uy8r8.mongodb.net/VedrunaApp?retryWrites=true&w=majority&appName=Cluster0
      
springdoc:
  api-docs:
    enable: true
    path: /v3/api-docs
  swagger-ui:
    path: /
